services:
  db-main: 
    image: mariadb
    environment:
      - MARIADB_ROOT_PASSWORD=geheim
    restart: on-failure:10
    volumes: 
      - db-vol:/var/lib/mysql

  pma: 
    image: phpmyadmin
    environment:
      - PMA_HOST=db
    ports:
      - 6080:80
    restart: on-failure:10
    depends_on: 
      - db

  web: 
    image: nginx
    volumes: 
      - ./paradox-gym:/usr/share/nginx/html:ro
    ports: 
      - 80
    deploy: 
      replicas: 10

volumes: 
  db-vol:
    name: db-vol-name
