version: '3.9'

services:
  web: 
   image: nginx
   environment: 
     HALLO: "Welt!"
   configs: 
     - source: web-html
       target: /usr/share/nginx/html/index.html
   ports: 
     - 9095:80
   deploy:
     replicas: 4

configs: 
  web-html: 
    file: "index.html.tmpl"
    template_driver: golang
