apiVersion: apps/v1
kind: Deployment
metadata:
  name: paradox-gym-deployment
  labels:
    app: paradox-gym-deployment
    version: "1.0"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: paradox-gym-server
  template:
    metadata:
      labels:
        app: paradox-gym-server
    spec:
      containers:
        - name: paradox-gym-server
          image: paradox-gym:1.0
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: paradox-gym-service
  labels:
    app: paradox-gym
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: paradox-gym-server