version: '3'
services:
  db: 
    image: mariadb
    environment:
      - MARIADB_ROOT_PASSWORD=geheim
    restart: on-failure:10
    volumes:
      - db-vol:/var/lib/mysql

  pma: 
    image: phpmyadmin
    environment:
      - PMA_HOST=db
    ports:
      - 6080:80
    restart: on-failure:10
    depends_on: 
      - db

  web:
    image:nginx
    volumes:
      - type:bind
        read_only: true
        source: ./example
        target: /usr/share/nginx/html:ro
#      - /Users/example:/usr/share/nginx/html:ro
    ports:
      6081:80

volumes:
  db-vol:
    name: db-vol-name