apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app-redis
  labels: 
    app: flask-app
    part: redis
spec: 
  replicas: 1
  selector: 
    matchLabels: 
      app: flask-app
      part: redis
  template: 
    metadata: 
      labels: 
        app: flask-app
        part: redis
    spec: 
      containers: 
        - name: flask-app-redis
          image: redis:7.0.5
          ports: 
            - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata: 
  name: flask-app-redis
  labels: 
    app: flask-app
    part: redis 
spec: 
  type: ClusterIP
  ports: 
    - port: 6379
      targetPort: 6379
      protocol: TCP
  selector:
    app: flask-app
    part: redis