services:
  db: 
    image: mariadb
    environment:
      - MARIADB_ROOT_PASSWORD=${DB_PASSWORD}
    restart: on-failure:10
    volumes: 
      - db-vol:/var/lib/mysql

  pma: 
    image: phpmyadmin
    environment:
      - PMA_HOST=db
    ports:
      - 6080:80
    restart: on-failure:10
    depends_on: 
      - db

volumes: 
  db-vol:
    name: db-vol-name4
